import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { LockfileSchema, type Lockfile, type LockfileInstallation } from "./types.js";

const LOCKFILE_NAME = "skillpack-lock.yaml";

/**
 * Get lockfile path relative to config path
 */
export function getLockfilePath(configPath: string): string {
  return join(dirname(configPath), LOCKFILE_NAME);
}

/**
 * Read and parse existing lockfile, or return null if not found
 */
export async function readLockfile(lockfilePath: string): Promise<Lockfile | null> {
  if (!existsSync(lockfilePath)) {
    return null;
  }

  const content = await readFile(lockfilePath, "utf-8");
  const parsed = parseYaml(content);

  // Validate with schema
  const result = LockfileSchema.safeParse(parsed);
  if (!result.success) {
    // Invalid lockfile, treat as if it doesn't exist
    return null;
  }

  return result.data;
}

/**
 * Create a new empty lockfile
 */
export function createLockfile(): Lockfile {
  return {
    generated: new Date().toISOString(),
    installations: {},
  };
}

/**
 * Update lockfile with new installation
 */
export function updateLockfile(
  lockfile: Lockfile,
  repo: string,
  installation: LockfileInstallation
): Lockfile {
  return {
    generated: new Date().toISOString(),
    installations: {
      ...lockfile.installations,
      [repo]: installation,
    },
  };
}

/**
 * Write lockfile to disk
 */
export async function writeLockfile(
  lockfilePath: string,
  lockfile: Lockfile
): Promise<void> {
  const header = "# Auto-generated by skillpack. Commit this file to git.\n\n";
  const content = header + stringifyYaml(lockfile, {
    lineWidth: 0, // Don't wrap lines
    defaultStringType: "QUOTE_DOUBLE",
    defaultKeyType: "PLAIN",
  });
  await writeFile(lockfilePath, content, "utf-8");
}

/**
 * Check if a repo+skills combo is already installed with same commit
 */
export function isAlreadyInstalled(
  lockfile: Lockfile | null,
  repo: string,
  skills: string[] | "all",
  agents: string[]
): boolean {
  if (!lockfile) return false;

  const existing = lockfile.installations[repo];
  if (!existing) return false;

  // Check if all agents are covered
  const allAgentsCovered = agents.every((a) => existing.agents.includes(a));
  if (!allAgentsCovered) return false;

  // If requesting "all", check if we installed "all" (we track this as empty array)
  if (skills === "all") {
    // We can't know for sure without re-fetching, so be conservative
    return false;
  }

  // Check if all requested skills are installed
  const allSkillsCovered = skills.every((s) => existing.skills.includes(s));
  return allSkillsCovered;
}
